### ISSUE TITLE
Addition of non-Latin characters in alphabetizing causes alphabet to be cut off

### ISSUE THREAD

**Issue by Scefing** [CDrummond/lms-material#127]
I have several albums from Japan, and, as you might expect, the names start with Japanese characters. These are organized in the correct order in LMS, but when using the material skin, I'm unable to see the full alphabet selection in the alphabet selector because it's longer than the skin expects. 

![Screenshot_20190614_155134](https://user-images.githubusercontent.com/921547/59534637-e9432b80-8ebc-11e9-93c0-4d10e82490a1.png)

You can see the letter S and beyond don't appear because of the Japanese characters that are alphabetized before them. If I expand the window, I get more of the alphabet, but it's annoying to always have to do that.

**Comment by CDrummond** [comment]
Material does not care about the language - it gets the letters for the 'jumplist' from LMS. Each Album wil have its 'textkey' - Material stores the index of the 1st occurrence of each unique letter. However, when there is insufficient space for all letters, Material attempts to squash the list - by removing some letters. Hence why even some of the Latin characters are missing. So, no this has nothing to do with character set. There are simple too many letters to show. If you expand the window more should be shown.

This is by design.
