### ISSUE TITLE
display & link issue in both Desktop & Mobile (1.1.2)

### ISSUE THREAD

**Issue by d6jg** [CDrummond/lms-material#186]
**Very** minor display & link issue in both Desktop (Grid & List) and Mobile (1.1.2)

Artists

![image](https://user-images.githubusercontent.com/47001366/68122908-6ec68700-ff03-11e9-8f08-6bec80c99c50.png)

Select an Artist (BBM) / Show Album / Select More

![image](https://user-images.githubusercontent.com/47001366/68122925-7dad3980-ff03-11e9-9338-ac134eed3aba.png)

Select another Album Artist (Ginger Baker - multi tagged)

![image](https://user-images.githubusercontent.com/47001366/68122959-8bfb5580-ff03-11e9-8715-4728931575a1.png)

Original Artist (BBM) is shown again as Link

![image](https://user-images.githubusercontent.com/47001366/68123060-db418600-ff03-11e9-8f68-91d4847b412e.png)

Follow Link (BBM) - wrong Artist displayed / no Links

![image](https://user-images.githubusercontent.com/47001366/68123330-83574f00-ff04-11e9-83b9-872b275c4c4c.png)

**Comment by CDrummond** [comment]
Artist album listings have no artist shownas you are showing this artists albums - so no point. At least not in my collection.

The problem is when you click on "AlbumArtist: George Baker" (or whatever), I ask LMS for albums using the supplied artist_id. LMS gives me a list of albums (good), but they all have the same artist_id. When you click on a link (in the penultimate screenshot), I ask for albums of artist_id as supplied by LMS.

My work-around would be to simply not have the artist (and hence link) on the penultimate screenshot.

You can verify this be looking at the JSON debug messages of LMS's responses.

**Comment by d6jg** [comment]
I think it is probably better as it then.

**Comment by CDrummond** [comment]
No. I can't leave it broken - so I will remove the sub-title (artist name). And before you ask, no I cannot leave this but just remove the link.

**Comment by d6jg** [comment]
😊

Kind regards


Jim Gooch
Director
Double 6 Ltd
Direct Line +44 (0) 845 508 1950
Mobile  +44 (0) 7802 550302
Support +44 (0) 1270 898 044
VOIP 8120540@draytel.org<mailto:8120540@draytel.org>
Skype double6jg
www.double6.net<https://www.double6.net/>
