### ISSUE TITLE
larger input fields in the desktop layout ?

### ISSUE THREAD

**Issue by eseb63** [CDrummond/lms-material#269]
hello, and thanks for your great work ...

on my desktop, i don't see any difference between mobile and desktop layouts for the server settings ; for some plugins (like erland custom scan) one have to enter a comma separated list which can potentially be quite long, but only 2-3 terms are visible so it' s not very comfortable and frustrating as there is more space in the screen ...

which enhancement could be done ? might the input fields be larger and/or multiline in the desktop layout ? or at least have a tooltip to see all the text if too long for the field?

thanks in advance for your reply

**Comment by CDrummond** [comment]
Just installed Custom Scan so that I could see the issue. Yeah, some fields are small. But then I checked with the default web UI skin, and they are small too.

Material does not set the size of these fields - only a min size and a max size (which is the view width - 32px). Its up to the plugin author to decide what width of text field they want.
