### ISSUE TITLE
Provide settings to edit actions.json

### ISSUE THREAD

**Issue by XavierP56** [CDrummond/lms-material#277]
Hi,

Daphile provides no SSH access so I can NOT edit the Material Plugin actions.json file.
Can you provide a basic editor for it through the settings ?

The idea behind this:
I could send the ramplay start command from the Menu and have Daphile doing the Ramdisk playing !

Many thanks.

**Comment by CDrummond** [comment]
No. Fix Daphile.

**Comment by XavierP56** [comment]
Hi,

Daphile provides no ssh on release version so I can not edit the
action.json file.
This won't change.

Being able to edit the action.json from the setting would be a way to
workaround it...

Best Regards,
Xavier.

**Comment by CDrummond** [comment]
I realise you are passionate about daphile, but I will **not** amend Material to work around its deficiencies. 

The issue is with daphile not allowing you access - again a daphile issue.

Still just create an LMS plugin to active this ramdisk - problem solved, and in a consistent manner for all UIs, etc.
