### ISSUE TITLE
material skin not working with IPAD 2

### ISSUE THREAD

**Issue by jrrolorin** [CDrummond/lms-material#327]
I have installed material skin on several Lms (windows, Synology, Gentoo, Daphile) and I have never be able to use the interface with iPad 2. Standard interface works as well as Daphile interface. I have enabled the JavaScripts. It seems that iPad 2 support HTML 5. I have used both Safari and Chrome but what I get is always a blank screen. I suspect it could be an intrinsic limit of the IPAD 2.

**Comment by CDrummond** [comment]
Sorry, but this is iOS and apples fault. On iOS there is only one browser engine (the part that renders pages and JavaScript), all others (Chrome, Firefox) are just different 'skins' for this. And, unlike Android, the browser engine is only updated with the whole os - how silly!!

So, due to Apple, your browser is too old and there is nothing that can be done about it.

**Comment by jrrolorin** [comment]
Thank you for the promptly answer. Just for curiosity which is the characteristic that is not implemented in the old engine ? Is it due to the JavaScript or to the HTML5 ?

**Comment by CDrummond** [comment]
I'd imagine it's the Javascript engine, but without such a device I don't really know. If only Apple weren't such control freaks you could install a real alternative browser with an up-to-date backend.
