### ISSUE TITLE
Generic app icon SVG support

### ISSUE THREAD

**Issue by CDrummond** [CDrummond/lms-material#431]
Perhaps if app icons were named blah.svg.png then Material could look for blah.svg?

**Comment by CDrummond** [comment]
Radio France and Virgin are missing Material icons

**Comment by CDrummond** [comment]
Radio france icon added. Generic plugin icon mapping added for 2.3.0, and i use by VirginRadio plugin,

**Comment by expectingtofly** [comment]
Unfortunately this causes havoc with LMS image resiser and breaks images : it does things like this : 

http://172.16.0.8:9000/plugins/VirginRadio/html/images/VirginRadioLogo.svg_50x50.png

placing the rename after the .svg instead of at the end breaking the link.

Is it worth switching to your other idea of using underscore?

**Comment by CDrummond** [comment]
Ah! OK, lets switch to an underscore. - so `xxx_svg.png` (just being 100% clear)
