### ISSUE TITLE
feature request: jump to Player via URL

### ISSUE THREAD

**Issue by hismastersvoice** [CDrummond/lms-material#45]
Hello,

I´m happy about this great Theme, and like to integrate this into my Smarthome Control.
The only thing I miss, is to Jump direct to a Player. Like ...../material/desktop.html?player=aa:bb:cc:dd:ee

So I can set a link for each room in the UI of my Smarthome-Sysetm
Is this possible? 

Thanks for that great work!!!

**Comment by duncanhancox** [comment]
thanks a million for this - it works brilliantly

is it possible to support the player name in the url as an alternative to the mac address? 
eg http://ip-address:9000/material/mobile.html?player=kitchen

a player can then be replaced in squeezebox server without having to recode the interface links in home automation systems

**Comment by CDrummond** [comment]
No, sorry. Currently material saves the current player's MAC into local-storage, so that this player can be selected when re-started. The ?player=mac simply writes the supplied MAC to local storage, so that the existing mechanism thinks that was the last player.

Mapping from name->mac would be possible - but its not a use case that this skin needs. Sorry, but I'm not about to add lots of little hacks for user specific use cases. You could write a simple script that maps name->mac and then supply the MAC to material.

**Comment by CDrummond** [comment]
...actually this was **much** simpler than I thought - so implemented now :-)

**Comment by duncanhancox** [comment]
thanks a million
