### ISSUE TITLE
Media Key Control

### ISSUE THREAD

**Issue by jollybully** [CDrummond/lms-material#482]
Great work on Material Theme - it's been my default gui for some time now. Brilliant brilliant work modernising the LMS interface.

Is there any way to integrate with my system media keys to control playback of the currently selected player via chrome's media controls?

<img width="415" alt="Screenshot 2021-05-05 at 10 47 33" src="https://user-images.githubusercontent.com/28121971/117123758-5735bc00-ad8f-11eb-80f8-2c4dff3dac29.png">

**Comment by CDrummond** [comment]
This would require a 'MediaSession'. Material used to support this, so that lock screen controls showed on Android, etc. Unfortunately, Material does not actually play any media and the code to fake this kept breaking - so was removed. In short, as Material is not actaully playing anything these controls dont work.
