### ISSUE TITLE
Error when installing in fresh Docker install

### ISSUE THREAD

**Issue by crosbyh** [CDrummond/lms-material#512]
Hello! Thank you for creating this wonderful-looking skin! I am trying out both LMS and your skin for the first time. I have a fresh docker install of the community image of LMS running. I seem to be able to install other plugins without issue, but when I attempt to install lms-material, the installation fails and my logs show the following message:

```
[21-08-10 11:59:31.2941] Slim::Utils::PluginDownloader::_installDownload (216) digest does not match /config/cache/DownloadedPlugins/MaterialSkin.zip - MaterialSkin will not be installed: expected 8d1c93f9ba60b922eccd6734eba1a74780bd7114, got 21651178282afa379e7c7f6dea4f3a7b8f98c0cd
```

Do you know what might be causing this? Thanks again!

**Comment by CDrummond** [comment]
I made a commit yesterday that incorrectly changed the sha1sum in public.xml - I've now fixed this.

However, downloads still fail - but I think that's due to Material being in LMS's 3rd party repo and that stil having the incorrect value. Hopefully this will be resolved in a few hours. Until then I'll reopen this.

**Comment by crosbyh** [comment]
Thanks for the quick response, I’ll give it another shot later on.

**Comment by CDrummond** [comment]
Can you try again? LMS's pugin repo has been updated.

**Comment by CDrummond** [comment]
Install now works for me.
