### ISSUE TITLE
Squeezesonic plugin not working when using Material theme?

### ISSUE THREAD

**Issue by Hukuma1** [CDrummond/lms-material#519]
Heya! Great work on this. The transformation is night and day.

I am trying to use LMS with plugin Squeezesonic which lets me pipe in my library from Navidrome using Subsonic API. It works and I can browse my media with the default interface skin. However once I install your Material theme I no longer see Subsonic listed under the Apps section.

I came across this closed issue here: https://github.com/CDrummond/lms-material/issues/375

Is there a way to make this specific plugin work without tying it to the online app store mysqueezebox.com? (like it does without Material theme)

**Comment by CDrummond** [comment]
Just installed squeezesonic and it is appearing for me.

As stated in the linked issue, the list of apps comes from LMS. If an app is not being returned then the issue is with LMS. Material is not like the Default skin, it uses a different API to get listings. Material is more like apps such as Squeezer, iPeng, etc. Do these also have issues listing Squeezesonic?

**Comment by Hukuma1** [comment]
Ah so this uses different API. Sounds like the immediate culprit. No chance of using the same API as the default skin?

I quickly loaded Squeezer just to test but all I saw was "player is not connected" and couldn't even browse to any apps. Not sure if that's intended behavior or not.
