### ISSUE TITLE
Add Music Source 

### ISSUE THREAD

**Issue by larod241** [CDrummond/lms-material#553]
Hello,

Would it be possible to add the broadcast source on the playback screen.
Either via a LOGO of the service (local, soptify, qobuz, ...), or via a text indication.

Ideally, just above the technical broadcasting information of which he can be part of elsewhere.

Thank you and happy New Year !!!

![IMG_5369](https://user-images.githubusercontent.com/20423481/147826467-9efd2831-4ef1-4bcb-9415-19e3e856eeaa.jpeg)

**Comment by CDrummond** [comment]
You can see the music source in the song info view, underneath the lyrics. I thought about adding the logo over the cover - but the issue is I'm not sure how to know where the top-right corner is! Sounds easy, but the browser decides upon the image scale, etc, so its not hard-coded. (And I'm not a web-developer!)

Not sure how this would look, but I'm considering showing the service logo semi-transparent underneath the title/artist/album lines. Might look a bit messy...

**Comment by larod241** [comment]
A little transparent seems to be a good idea so as not to be too visible and generate the rest of the information.

We have to test! :-D

**Comment by CDrummond** [comment]
...actually that would not work for landscape view. :(

**Comment by CDrummond** [comment]
I've added this info next to tech info. Will think about the emblem.

**Comment by CDrummond** [comment]
Sorry, I tried. Logo semi-transparent under text looked odd, and nowhere else to place. Top-right of cover would be best, but no idea how to do this - as CSS takes care of image size and position, so not sure where top right of image is.

However, if you show tech info then the service name is also shown.
