### ISSUE TITLE
Usability issue/request for transferring play queues

### ISSUE THREAD

**Issue by chrober** [CDrummond/lms-material#577]
Hi,

I use the feature to transfer play queues from one room to another quite often. However, when I hold my phone upright in portrait mode the transfer icon is hidden in the kebab menu, while in landscape mode the icon is visible. In contrast, the repeat, shuffle, save, and clear icons are always visible on my phone (see screenshots below).

I assume if there is enough space available the transfer icon is displayed right away and if there is not enough space it will be available via the kebab menu.

Here comes my request: I hardly press the repeat icon and I almost never press the shuffle, save, and clear icons (however, these are always visible). I would really want to have the icon I use most (transfer) to be visible all the time. I guess this could be achieved by placing it before the repeat and shuffle icons. Maybe the solution would be to offer a configuration possibility to reorder these icons manually?

What do you think?

![Screenshot_20220323-143857_Chrome](https://user-images.githubusercontent.com/26856218/159714364-3476dbcb-cd0e-48c6-a494-4ef41f88c810.jpg)

![Screenshot_20220323-150339_Chrome](https://user-images.githubusercontent.com/26856218/159717747-1bebe961-4d23-45a1-b0e8-0721cfabe420.jpg)

![Screenshot_20220323-150348_Chrome](https://user-images.githubusercontent.com/26856218/159717773-f21e6caa-bdc6-4a13-a41a-57c4f16c289b.jpg)

**Comment by CDrummond** [comment]
No, sorry - I like as is.

**Comment by CDrummond** [comment]
...perhaps, as a compromise, a long-press on the time field could show the transfer dialog?

**Comment by falkenhawk** [comment]
Hey @CDrummond, i've just learned about the long-press on the time field :) I was about to suggest to show the "transfer queue to another player instead of the "clear queue" button. (and move the clear queue to inside the three-dot menu)

Currently on desktop layout there are 4 buttons to the right of the "..." menu button - repeat, shuffle, save queue, clear queue
and on mobile the save button is moved inside the three-dot menu, and appears as the first item there, so 3 buttons remain in the toolbar - repeat, shuffe, clear queue.

I personally never use save/clear queue buttons.

But I suppose there are as many individual preferences as users - perhaps we could have the order of buttons configurable in the interface settings? 🤔 Or would that make it all too complicated?

As of now, there are several ways to move the current playlist to another player, starting from the "now playing" view: (on portrait/mobile layout)
1) tap queue on the bottom, tap three-dot menu in the secondary toolbar, tap "transfer queue" menu item which is second-to-top.
2) tap queue on the bottom, long-press the time field
3) long-press the image (context menu appears), tap "More", tap "Music, Walk With Me"

Ad. 1 and 2) having the "transfer queue" button in the secondary toolbar would make it easier and quicker to reach (by the amount of 1 tap or time spent on long-pressing less ;)
Ad. 3) perhaps it would be possible to display "Music, Walk With Me" already in the context menu? (for instance "Orange Squeeze" had it like that)

But honestly, I can live with how it is now. And it looks like my wife is used to Orange Squeeze too much to convince her to switch to using "LMS" app instead, and my daughter transfers her playlist from one radio to another, using on-device buttons to trigger "Music, Walk With Me" (which is reachable there after one button press from the "now playing" screen - so maybe it actually is another argument to consider unifying the behavior of the context menu mentioned in 3) with the flow on the hardware)

Thanks for bearing with me. You are doing amazing work. We are lucky to have you in the LMS community. Cheers
