### ISSUE TITLE
Support ID3 URL link frames

### ISSUE THREAD

**Issue by mforkel** [CDrummond/lms-material#629]
ID3 defines a set of [URL link frames](https://id3.org/id3v2.3.0#URL_link_frames). It would be great if it was possible to follow such links from the user interface.

**Comment by CDrummond** [comment]
Material Skin is just a web-app for LMS, it doesn't have access to the files themselves. Support for these would first have to be added to LMS.

**Comment by mforkel** [comment]
That is a convincing expllanation :-). I have created in [issue for LMS](https://github.com/Logitech/slimserver/issues/842), asking for access to link frames.

**Comment by mforkel** [comment]
I have now upgraded to Material Skin 3.1.0 and can see my WXXX tags, both description and URL.

In Firefox 108.0.2 on Windows 10 the URL is shown in blue, a click opens a menu with the commands _Follow Link_ and _Search_, and I can open the link in a new tab. Great!

But in Safari on iPadOS 15.7.2, the URL is as white as its description and not "clickable", so I can't follow the link.

**Comment by CDrummond** [comment]
Well my guess is this is a Safari issue. Michael added a search and replace regex to Material:

```
 i.title = i.title.replace(/\b(https?:\/\/[A-Za-z0-9\-_\.\!~*'();\/?:@&=+$,]+)/, "<a href=\"$1\" target=\"_blank\">$1</a>");
```

This will covert the URLs to clickable links. If this is not working its probably due to Safari's poor JS engine that fails to do the replacement above. This is not the first time that Safari has failed to parse a regex.
