### ISSUE TITLE
Top or bottom of page cut off. Only one can be shown. - Google Chrome - Android

### ISSUE THREAD

**Issue by MauricioFarias** [CDrummond/lms-material#684]
When I load the page, it is showed OK, but when I use it, top or bottom cut off.
I use swipe to change volume so I can not swipe to access to top or to bottom.
This behaviuor started with recent updates. In previous versions worked ok.
It happens in mobile mode.

Server:
Version: 8.3.1 - 1676361197 @ Fri Feb 17 06:33:29 WEST 2023
Operating system: Windows 10 - EN - cp1252
Platform Architecture: 8664
Material Skin (v3.3.4) 

Client:
Android 10
Google Chrome: 114.2.5735.130

![2023-06-23 16 59](https://github.com/CDrummond/lms-material/assets/4921702/077ba26f-c613-49e9-a3d1-3caaf9340bad)

**Comment by CDrummond** [comment]
Sorry, but I cannot recreate this on my S20FE - but this has Android 13.

You say it was working before, so I'm going to need you to locate the last version that did work - so that I can do a diff and see what might cause this.

All releases are on Github. What you need to do is download a release (e.g. https://github.com/CDrummond/lms-material/releases/download/3.3.0/lms-material-3.3.0.zip), unzip its contents over the MaterialSkin folder in your LMS install, restart LMS, clear Chrome's cache, kill the WebApp, and reload.

To make things easier I suggest you try each minor version first - so 3.2, 3.1, 3.0 Then if 3.1.0 works, but not 3.2.0, then try 3.1.1, 3.1.2, etc.

**Comment by MauricioFarias** [comment]
Thanks for the quickly response.
I found that WebApp display parameter set in Fullscreen causes the issue.
If I set to Standalone, material skin works ok.

![2023-06-23 18 02](https://github.com/CDrummond/lms-material/assets/4921702/4bc3d5a5-922f-4e3c-bdf5-bb03964374d5)

**Comment by CDrummond** [comment]
Yes, but that is only a work-around. It does not solve the actual issue you are seeing. A better work-around is to use the APK (https://f-droid.org/en/packages/com.craigd.lmsmaterial.app/) - this is a WebView wrapper. However, it'd be better to solve the actual issue. For that I will need your help as described.

**Comment by MauricioFarias** [comment]
Of course, it is a workaround but the bug is more accurate. I will help you to solve this issue. 
I will try to fdroid app too... I did not know about it .
