### ISSUE TITLE
Feature request: album art - rounded corners 

### ISSUE THREAD

**Issue by artatgray** [CDrummond/lms-material#701]
Hi devs,

As mentioned in the title, the option to round the corners of the album art would be very nice, and would offer a more contemporary aesthetic as numerous music player/client applications now do so.

Here's an example:

https://imag.malavida.com/mvimgbig/download-fs/symfonium-35768-1.jpg 

Please consider it.

Regards,
Bill

**Comment by CDrummond** [comment]
I'd love to do that, and have often thought of adding it. The only problem is I don't know how.

I know you can give CSS elements a rounded border, and that's trivial todo. The issue with these cover images is that I use CSS's "object-fit:contain" to scale (up or down) the image horizontal/portrait so that they fill the space. Because of this there can be padding left/right or top/bottom - and I don't know where.

I've just tried using a SVG filter (as described in https://stackoverflow.com/questions/49567069/image-rounded-corners-issue-with-object-fit-contain) and whilst this does work, it slows scrolling of the grid view quite a bit. (If images are to be rounded then they should be rounded everywhere).

If you know of any better/faster way I'm happy to implement. (As stated multiple times, I am not a web developer).

**Comment by CDrummond** [comment]
...but using standard CSS for grid/list seems fast enough, and using an SVG filter for now-playing works there (and only one image so no real performance impact).

**Comment by artatgray** [comment]
If I can find a web developer willing to donate a bit of their time to work with you on it, would you be open to it?

Regards,
Bill

**Comment by CDrummond** [comment]
I closed the issue as it's been implemented - if you view in github you can see the "closed as completed in XXXX".

I use plain CSS rounding for the list/grid view, and then use the SVG filtering for the now-playing large cover-art. This will be in 3.4.2

**Comment by artatgray** [comment]
Great! Thanks... 😎
