### ISSUE TITLE
Add artist's name to Album Tracks page

### ISSUE THREAD

**Issue by maidentaiwan** [CDrummond/lms-material#702]
(This is an enhancement request.) On the page that list all the tracks in an album, would it be possible to display the artist's name somewhere? You show the album title and year, but not the artist.

For example, in the attached image, the artist's name is Kansas but it doesn't appear anywhere on the page.

Thank you very much for a fantastic UI for LMS!!

![kansas-screenshot](https://github.com/CDrummond/lms-material/assets/4689691/a50d868d-9796-43a8-865a-e77df00b6080)

**Comment by CDrummond** [comment]
Ideally I'd want the "title" line to be "Album Artist - Album Name (Year)", and if there is insufficient space then just "Album Name  (Year)", and further truncating to "Album Na..." if still too little space. The problem is I don't know how to achieve this!

The simplest solution is to have "Album Name (Year) - Album Artist" and then just use ellipsis on the right if insufficient space. But this looks a little odd.

**Comment by maidentaiwan** [comment]
For the second solution, if there is insufficient space, could you make the whole Artist Name appear if you hover your mouse over the incomplete name? The skin already does it on the list of albums (see pic):

![gicwe](https://github.com/CDrummond/lms-material/assets/4689691/d091acfa-f0ab-442e-a1b7-9fb51040df61)

**Comment by maidentaiwan** [comment]
Thank you!
