### ISSUE TITLE
Podcasts not editable in Favorites

### ISSUE THREAD

**Issue by Enrico17024** [CDrummond/lms-material#775]
I'm a superhappy Material Skin User since the beginning, so a big thank you to the developers!

I wanted to edit a Podcast entry in Favorites, all empty fields exept the title (see Screenshot 1). So I do it in the StandardUI an edit is easy possible (see Screenshot 2). I did the setup of the Podcasts listed in the Favorites in Settings -> Plugins -> Podcasts (see Screenshot 3).
As it works in the old StandardUI, I believe it's simply a bug and therefore I've entered here in Github, I hope ok so :-)
Thanks for any follow up.

Cheers
Enrico

![EditInMaterialSkin](https://github.com/CDrummond/lms-material/assets/151435742/a31e86b7-d6ec-47c9-adfb-e87d3f7ad3de)
![EditInClassicUI](https://github.com/CDrummond/lms-material/assets/151435742/f684f7ca-160e-4e34-9abb-80116e7a844a)
![PodcastEntries_inSettings](https://github.com/CDrummond/lms-material/assets/151435742/a4f1b78c-20fc-43e6-8956-df8f673f04d8)

**Comment by CDrummond** [comment]
Unfortunately LMS is not providing the 'preset parameters' for this item. These contain the URL, title, and image - title and image duplicated elsewhere, hence shown here. But, without the 'preset params' Material cannot editing anything, hence for the next release I'll hide the 'Edit' action for such items.

However, the issue is with LMS - it should provide the 'presetParams' attribute.

As to how Default skin works, not sure. I know it uses a different API to Material. Material is more like an app (Squeezer, iPeng, etc.) than a skin.
