### ISSUE TITLE
playlist - random playback mode selection issue

### ISSUE THREAD

**Issue by klslz** [CDrummond/lms-material#790]
A feature wish... (Not sure if it is a bug)

When selecting an album or playlist from the browse menu with "Play now" I do not seem 
to have a chance to select the "Random" playback option during the process. 

Before pushing "Play Now" the playback symbol is dimmed, which prevents from changing 
to random mode on the playback screen,
and during playback it's not possible, since the playlist is already loaded.

I am not sure when to select random mode?? During the prior playback session ?
The next Q would be how to turn it off again, when going back to normal.

I am ( and I know many other people as well) using more and more long playlists from services like Qobuz or Spotify.
Therefore the Random function comes in very handy for me nowadays.

If there is a nice way to get "Random playback" on/off nicely, please let me know.

**Comment by klslz** [comment]
You're quick on the closing!
OK. 

Do I got it right that  I need to "shuffle" the playback-playlist after I loaded a stored playlist or album from the browser,
while the playback already started?


Or do I need to turn shuffle on the playback screen first and then go back to the browser screen to push "play now". 

To play with shuffle I always need to enter the playback screen first, do the changes, and then go back to browse menu.

OK. Just to mention it.
It can also work less complicated:
The iOS  Qobuz app offers a "shuffle-play" icon and a normal "straight-play" icon in its browse menu. Whatever
you push - playback will start immediately in that mode. IMO much more intuitive and much less hassle.


Anyhow. Thx for the great UI.

**Comment by CDrummond** [comment]
Just for background... I had thought about trying to automate this. i.e. place LMS in shuffle mode, then add album/etc. to queue. This would achieve what you are asking for (and could be done via 1 button/click.) The issue is now that LMS is in shuffle mode so if you subsequently just use the add or play buttons, the queue is still in shuffle. In my mind if a "play album shuffle" button existed I'd expect the "play album" to play non-shuffled. So, I could also do that - so that the add/play buttons set the queue to non-shuffled mode. But, that then breaks users who've explicilty set the queue to shuffle and then want to add another album.

So, sorry , as LMS currently stands I see no easy way to implement this whislt also keeping current behaviour. Easiest way is to just put queue into shuffle mode and then add album.

**Comment by CDrummond** [comment]
FYI, this is now in 4.1.0

**Comment by klslz** [comment]
Thx. I did try it. Turned it on inside the LMS/material-UI settings. I am not sure how to access it from the Material-UI though !?! On the first glance there are no new buttons. Not sure how this is supposed to work. Sorry for my ignorance.

**Comment by CDrummond** [comment]
It's in the "..." menu.

**Comment by klslz** [comment]
I figured it out now.

I didn't see it because it is not showing up inside the Qobuz menus. And these I use 99.9% of my time. ;)
The new feature works as suggested for local music though.

**Comment by CDrummond** [comment]
Sorry, don't use streaming services.

**Comment by CDrummond** [comment]
Will see about adding there.

**Comment by klslz** [comment]
I checked the Qobuz menus last night. "Play Shuffled" also shows up there now. Great. A very nice and useful new feature.

Thx a lot.
