### ISSUE TITLE
iOS17: whitebar permanently visible

### ISSUE THREAD

**Issue by klslz** [CDrummond/lms-material#810]
MaterialSkin:  4.1.1
iOS: 17.2.1

It's me once more. Just wanted to document the issue. It's not critical.

The iOS whitebar remains visible all the time at the bottom of MS . 
It is afaik supposed to fade out after a while or should not be visible at all.

In the past there were tries on different other web-apps out there  to get it done similar to this way:

`  <meta content="black-translucent" id="status_bar" name="apple-mobile-web-app-status-bar-style" />`

However in several cases that turned out to be  insufficient. I couldn't find any recent discussions about the subject.

I've seen that you use "black" and not "black-translucent" in index.html .  Not sure if that'd be a hook.

Anyhow. It'd be nice to get rid of that iOS whitebar if it is not too much effort. 

Thx for your efforts.

**Comment by CDrummond** [comment]
No, sorry this is a **STUPID** iOS thing. I do not have an iOS 17 device and no motivation to waste even more time on silly stupid issue like this, which the OS should handle - not leave it up to web pages/sites to know how to interact with a device. By all means try replacing Material's "black" with "black-translucent"  - if that works I'll make the change. Then no work-around with adding padding would be required. s.

**Comment by klslz** [comment]
I don’t think it is iOS 17 only. And yes it’s stupid. People having similar issues for years. However. It is still a visible flaw on a UI. 

My web design skills are quite limited. On top comes that LMS beast you better don‘t touch. I can’t be of help beyond testing and reporting.

BTW. Material Skin is a tiny part of my own massive project.  You can believe me that I am not happy to spent hours on MS myself. But. If the UI sucks the whole project suffers. In todays world minor UI issues get a huge weight on the users opinion about the product/service. No matter if it is commercial or foc.

I think over the last couple of days MS improved a lot.
The whitebar is actually the last thing that‘s bugging me at the moment.

**Comment by CDrummond** [comment]
Its a flaw with Safari, or iOS - I only mentioned iOS17 as you state that version, and I have no access to it. I have tried setting Material to fullscreen, setting black-translucent, all to no avail. Not sure what else you expect of me? I am not a web developer, this is my first and only Javascript project.

If the "UI sucks" simply because of this, then its Safari/iOS's fault. As stated, if you can find a fix I'll gladly merge.

I'm not an iOS user - can't stand the restrictions (only 1 browser engine, can't install apps from elsewhere, etc.). However, I've tried on my wife's iPhone and even here with plain Safari the bottom/home bar stays. I think there's an accessibility setting to help with this.

But I've closed this issue as I will not be spending time on it. The padding was added so that this bar does not get in the way. Why iOS can't at least just make it semi-transparent?

**Comment by klslz** [comment]
Look. Don't get me wrong. You've built an excellent application. 
It puts all other LMS controller apps to shame and that includes iPeng.

And me and thousands other very happy users highly appreciate your efforts.

Happy holidays.

**Comment by klslz** [comment]
There is a (pretty lame) workaround. Under iOS you can turn Guided Access under Accessibility on.
If you then open MS via HomeScreen icon and start Guided Access with a tripple-right-side-button-click you basically lock the app and put the phone in single-use mode. Only then the whitebar disappears!

**Comment by CDrummond** [comment]
Well a work-around is better than nothing.

As stated I don't personally have any use for iOS, hence not willing to spend a massive amount of time on an issue which, IMVHO, is a Safari/Apple issue. But if you ever find a real solution I'm happy to merge it.

**Comment by klslz** [comment]
I today tried all kind of hacks related to index.html  that I found on the web. Nothing worked.

BTW. I am a die-hard fan of Linux for decades (professionally and privately). 
However. After fiddling around with Android for a while, I have to say: Never again! 
iOS simply works. Support is awesome. Interwork is awesome. No way I go back to Android.

**Comment by CDrummond** [comment]
I'm not trying to persuade anyone to use Android, or any other OS. I have my _personal_ reasons why iOS just does not work _for me_ - but this is purely personal. My wife loves her iPhone, and I have never tried to persuade her otherwise. I just prefer my freedom, and feel iOS does not respect that (privacy yes, freedom no). iOS interwork is great between other Apple products, as to be expected. Interwork with others, no. It's also a great OS, easy to use, etc. But, as stated I don't like being told what I can and cannot do with my own device. But that's just me. Not saying Android is perfect, far from it. But (IMHO) iOS being bad does not mean Android is good.

Working on this skin has made me realise how much Apple holds back on WebKit, how its more crippled than it needs to be. All so webapps are not as good as real apps, therefore more store purchases. Which is fine, Apple are there to make money after-all (and are very good at that). It's just not for me. Works for you, then great - that's your choice, and I respect that.
