### ISSUE TITLE
Why can't I see the "Albums" icon?

### ISSUE THREAD

**Issue by theone11** [CDrummond/lms-material#866]
I am running the latest LMS (v8.5.0 - 1710422688) and lms-material plugin 4.4.1 and when I enter the "My Music" section I can't see the "Albums" icon to enter the Albums view

![image](https://github.com/CDrummond/lms-material/assets/3348953/33951b1e-7d62-4c81-a727-bba1e3cb0f93)

**Comment by CDrummond** [comment]
You have enabled 'Release type support' in LMS. This then splits (what was) "Albums" into "Albums", "EPs", "Singles", etc. With this enabled it makes no sense to refer to a list of "Albums, EPs, etc." as "Albums" - because it contains more than albums. And if, for example, you _only_ had "EPs" then if "Albums" were used as the title here when you browsed Material would state (e.g.) "100 EPs" - again no sense. For this reason Material changes the string to "Release" - but the view when entered is the same.

If you want an explicit "Albums" view that _only_ contains albums you can use "Extended Browse Modes" -e.g.:

![image](https://github.com/CDrummond/lms-material/assets/1141694/f5165a82-bd58-483d-8540-d86c4f624a7d)

...which leads to:

![image](https://github.com/CDrummond/lms-material/assets/1141694/6017c005-171c-4363-9a04-f77eea1d209f)
