### ISSUE TITLE
LMS's language setting is ignored

### ISSUE THREAD

**Issue by chrober** [CDrummond/lms-material#89]
The Material Skin seems to use the language settings of the OS where the browser runs.
While this is a good idea from a usability perspective I would still prefer to choose the UI language on my own.

In LMS's "Basic Settings" there already is a language property (which differs from the OS's language setting in my case). Thus, I would expect the player UI to respect this setting. Or have at least a UI setting for choosing between the OS's language and the LMS's language.

**Comment by CDrummond** [comment]
Material does use this setting, and I have jsut confirmed by setting my LMS language to German. **However**, Material uses its own translation files - of which there are German, French, and Dutch. Only German is up-to-date.

**Comment by chrober** [comment]
Pretty strange. On a German Win10 having LMS set to English I still get a German UI in three different browsers: Firefox, Chrome, and Edge.

**Comment by CDrummond** [comment]
Can you open your browser's developer tools, and type:
```
(window.navigator.userLanguage || window.navigator.language).toLowerCase()
```

What does this return? My guess is its `en-us`. Material queries the LMS language. If this is set to `en`, Material queries the browser (using the above) to determine the variant. In my case this is `en-gb` But, if its `en-us` it is ignored. Falling back to using the LMS setting.

This should be fixed in the next release. Or you can checkout the git/master version.

**Comment by chrober** [comment]
Firefox is telling me "de-at", Chrome says "en".
Nevertheless, both browsers display the Material Skin in German language.

I just tried the following in addition:
I opened up the "default" player UI using `http://<IP_ADDR>:<PORT_NUM>/default/` and in Chrome and Firefox this is correctly being displayed in whatever language I set in LMS's "Basic Settings".
