### ISSUE TITLE
Random mix no longer working after updating to 5.1.0

### ISSUE THREAD

**Issue by orosoiu** [CDrummond/lms-material#926]
Hello,

I use LMS v8.5.2 in desktop mode and I have "Random Mix" pinned on my homepage as this is my preferred way to start listening to music. After updating to MS 5.1.0, the "Random Mix" option stopped working, opening a blank page instead of the popup to configure and start listening (see attached image).

Is there a way to make this option work again or otherwise revert to a previous version of MS?

Action: click on "Random Mix" menu option to start listening to music
Expected result: a config popup opens up allowing configuration of mix and start of playback
Actual result: an empty page with no actions is opened

Let me know if more information is required.

![Untitled](https://github.com/user-attachments/assets/1277e7b3-a78b-446e-9422-d5faf5bace48)

**Comment by CDrummond** [comment]
For 5.1.1 I have resolved this so your pinned link will work. However, I've moved 'Random Mix' to the queue menu as its not really a browse mode - no browsing!

BTW, with LMS9.0 Material will also show a dice icon (instead of shuffle) if random mix is enabled - and clicking on that will allow you to stop the mix.
