### ISSUE TITLE
Alarms go off two hours late

### ISSUE THREAD

**Issue by dryusername** [CDrummond/lms-material#954]
Hi, I'm having an issue where alarms go off two hours late. I suspect thia is because the alarms register to UTC, but my time zone is UTC+2.

It started around the time I switched to Material Skin. Not sure if it's a skin issue or a system issue.

![Screenshot_20240919-190641](https://github.com/user-attachments/assets/3150f278-61f8-4983-a79f-6ddf19961943)

**Comment by CDrummond** [comment]
Material does not know about timezone. If simply sends the time to LMS as seconds past midnight - as per https://lyrion.org/reference/cli/alarms/  The 'Default' skin sends time as strings (so '12:30') but the Perl code converts this into seconds since midnight.

So, if Alarms are wrong then this looks like an LMS issue.
